### ISSUE TITLE
Auto change redshift state

### ISSUE THREAD

**Issue by RMTT** [manilarome/the-glorious-dotfiles#114]
the `redshift` can change the state by itselt automatically, so can use the `redshift` automatically and get the current state on the lua module?

By the way, where is the commits, i found thousands commits become dozens commits now : )

**Comment by manilarome** [comment]
> the redshift can change the state by itselt automatically, so can use the redshift automatically and get the current state on the lua module?

Yeah, it's cool if the redshift widget will detect if the filter is on or off, but I don't think there's a way to get the filter's status. So currently, the best way to do is remove your redshift in your autorun applications and manually start/kill the redshift using the widget or keybind.


> By the way, where is the commits, i found thousands commits become dozens commits now : )

I moved the old history/commits in this [repo](https://github.com/manilarome/the-glorious-dotfiles-old). My reason for this is that the dotfiles became too heavy and cloning them is a pain in the ass because I have the slowest internet connection lol. Note that this is only temporary. I'll merge it if I found a way to lighten the size of it. My plan is to remove all the screenshots history.Tthat's why all the screenshots in README is now hosted by imgur.

**Comment by RMTT** [comment]
> I moved the old history/commits in this [repo](https://github.com/manilarome/the-glorious-dotfiles-old). My reason for this is that the dotfiles became too heavy and cloning them is a pain in the ass because I have the slowest internet connection lol. Note that this is only temporary. I'll merge it if I found a way to lighten the size of it. My plan is to remove all the screenshots history.Tthat's why all the screenshots in README is now hosted by imgur.

Is it possible to use ` git clone --depth=1'?

**Comment by manilarome** [comment]
> Is it possible to use ` git clone --depth=1'?

Yes. I'll merge it once I have clean it. Also, I really have a slow internet connection right now and github is always disconnecting.

**Comment by RMTT** [comment]
> > Is it possible to use ` git clone --depth=1'?
> 
> Yes. I'll merge it once I have clean it. Also, I really have a slow internet connection right now and github is always disconnecting.

All right, good luck : )

**Comment by manilarome** [comment]
> All right, good luck : )

Thanks! Already merged the old commits! Anyway, if I found way or if redshift devs implements a method to get the filter's status, I'll implement this.
