### ISSUE TITLE
[QUESTION][Floppy] Licencing a fork

### ISSUE THREAD

**Issue by ArtemSmaznov** [manilarome/the-glorious-dotfiles#127]
I am currently using your floppy configuration as a baseline for my own customization. I didn't fork it as I am planning on making a repository that will be an amalgamation of several different ones. 

As I am new to all of this I am not too familiar with the whole licencing concept. Any tips on how can I make sure I don't violate any terms and how do I properly link to your repository as the base? I potentially want to make sure my repository is licensed as well so others can use it if they want.

Here is the URL if you are interested to check out how I handled it so far:
https://github.com/ArtemSmaznov/dotfiles

Really loving your setup BTW - took a lot of inspiration from it

**Comment by manilarome** [comment]
> Any tips on how can I make sure I don't violate any terms and how do I properly link to your repository as the base?

Just include the licenses in your config. My setups are heavily based on PapyElgringo's [material-awesome](https://github.com/material-shell/material-awesome), that's why I included [its license](https://github.com/manilarome/the-glorious-dotfiles/tree/master/MORE%20LICENSES) to my repo. I also use the [rofi-web-search.py](https://github.com/pdonadeo/rofi-web-search) script by pdonadeo, so you'll also find its license there.

> Here is the URL if you are interested to check out how I handled it so far

See you on r/unixporn haha

> Really loving your setup BTW - took a lot of inspiration from it

thanks!

**Comment by ArtemSmaznov** [comment]
Thanks for the info I think it is clearer for me now
