### ISSUE TITLE
[BUG] Second monitor loses windows

### ISSUE THREAD

**Issue by PolarBean** [manilarome/the-glorious-dotfiles#141]
If I drag a window to my second display it is no longer accessible from the sidebar. This would not be a problem but if I open a new program and lose the original window there is no way to get it back and I'm forced to kill the program through htop. potentially a way around this bug would be to have a sidebar on both displays :) how would I go about doing this?

**Comment by PolarBean** [comment]
This is a great skin by the way :) I installed linux because of it.

**Comment by manilarome** [comment]
Assuming your using floppy because of the sidebar, change [these lines]
(https://github.com/manilarome/the-glorious-dotfiles/blob/12f54d1127d69c209a4bacf7609d2205cf5ed691/config/awesome/floppy/layout/init.lua#L7-L20) to this snippet:

```lua
screen.connect_signal("request::desktop_decoration", function(s)
	-- Create the left_panel
	s.left_panel = left_panel(s)
	-- Create the Top bar
	s.top_panel = top_panel(s, true)
	s.right_panel = right_panel(s)
	s.right_panel_show_again = false
end)
```

Anyway, you posted a duplicate [issue](https://github.com/manilarome/the-glorious-dotfiles/issues/140).

**Comment by PolarBean** [comment]
Ah the top bar loads but the side panels do not. it must be something weird about my setup. Thank you for trying!
