### ISSUE TITLE
error while running function

### ISSUE THREAD

**Issue by JoaquinDecima** [manilarome/the-glorious-dotfiles#152]
![Screenshot_20200713_185453](https://user-images.githubusercontent.com/11674229/87357517-84805780-c53a-11ea-9ee2-b558c681017a.png)

**Comment by manilarome** [comment]
What's the setup you're using? Anyway, please follow the format next time.

**Comment by JoaquinDecima** [comment]
Sorry, sorry you didn't follow the format. I am using Antix Linux (Debian based). I am using the "surreal" setup

**Comment by manilarome** [comment]
No problem.

Anyway, the error is weird because the line 60 of `theme/default-theme.lua` is just a path(string) and it's obviously not a null. https://github.com/manilarome/the-glorious-dotfiles/blob/f120c0565b945d204d9f83d68e4848d83a6d80c1/config/awesome/surreal/theme/default-theme.lua#L60

I can't also reproduced the problem here. Just make sure you're using the awesome-git-master branch. xsession-errors would be helpful too.

**Comment by JoaquinDecima** [comment]
Thank you for responding and for the information, since I apologize for the image, I hope it looks good, I think this information may be relevant to determine the error. I'm using Floppy the other day I got confused

Thank you very muchThank you for responding and for the information, since I apologize for the image, I hope it looks good, I think this information may be relevant to determine the error. I'm using Floppy the other day I got confused

![Screenshot_20200714_143727](https://user-images.githubusercontent.com/11674229/87459686-198a5b80-c5e2-11ea-9433-415c290131a3.png)

Thank you very much

**Comment by manilarome** [comment]
> awesome: Can't load GTK+3 introspection. Seems like GTK+3 is not installed or `lua-lgi` was build with an incompatible GTK+3 version.

Looks like we found the culprit. Just like the log said, it's either you don't have `gtk3` installed or `lua-lgi` was build with an incompatible gtk3 version. Here's the complete list of dependencies. https://github.com/awesomeWM/awesome/#build-dependencies
