### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by numine777** [manilarome/the-glorious-dotfiles#184]
Is there a way to run Kitty on WSL2?  I can get most everything else running smoothly, but keep getting OpenGL errors whenever I try to run kitty and I'm wondering if there's a workaround.  Thanks in advance!  This is easily my favorite config for awesome

**Comment by manilarome** [comment]
Kitty requires a *certain* version of opengl, iirc. So if WSL2 doesn't support it, kitty will not work.  [Here](https://github.com/kovidgoyal/kitty)'s a better place to ask this question, because I'm not really familiar how kitty works. Anyway, you can just use a different terminal emulator. So yeah, closing this now! Thanks!
