### ISSUE TITLE
[Question] How to display window title in titlebar ?

### ISSUE THREAD

**Issue by sennafaris28** [manilarome/the-glorious-dotfiles#193]
Hello there !  

So i am trying to edit some of your config, and when i tried to display the window title on the titlebar using the awful.titlebar.widget.titlewidget on the titlebar function, the window title still wont show up. Can you shed me some light on how to display it ? 

Sorry if this is a noob question, i'm new to ricing, and I've found your rice to be one of if not the best on r/unixporn !

**Comment by manilarome** [comment]
You should change [these](https://github.com/manilarome/the-glorious-dotfiles/blob/c2c618563221bf3f7eec164b7b842de2934831ea/config/awesome/floppy/module/titlebar.lua#L75-L78) lines(note that there are multiple instances of these) to something like this

```lua
        { -- Middle
            { -- Title
                align  = "center",
                widget = awful.titlebar.widget.titlewidget(c)
            },
            buttons = buttons,
            layout  = wibox.layout.flex.horizontal
        },
```

I can't really test it right now, because I'm using swaywm at the moment.

**Comment by sennafaris28** [comment]
turns out im and idiot and changed the color of the text to match the background :))))) thanks for your response !

**Comment by manilarome** [comment]
Glad you fixed it! No problem, you're welcome. Closing this now.
