### ISSUE TITLE
[Feature Request] Shared tags for multiple monitors

### ISSUE THREAD

**Issue by mgabs** [manilarome/the-glorious-dotfiles#197]
I'm using arch with dual monitors, awesome creates a separate tag list for each monitor, creating a total of 18 workspaces and I spend a decent amount of time searching between them.

I've search for a solution and found a plugin create by frioux that creates a shared tag list between the monitors and I've got it to work on vanilla rc.lua
https://github.com/frioux/charitable

However, I'm not able to integrate it cleanly with your moduler approach.

Can you help? include it as optional maybe to the current setup ?
or provide couple of pointers.

**Comment by manilarome** [comment]
I'm not really sure how `charitable` works, but looking at the code, you can mix it [here](https://github.com/manilarome/the-glorious-dotfiles/blob/master/config/awesome/floppy/configuration/tags/init.lua) where the tags are created. I don't use awesome anymore and only have a single monitor that's why I cannot test it right now. Closing this now. Good luck!
