### ISSUE TITLE
[Question] Not able to access Wifi interface from title bar and bottom pannel customization

### ISSUE THREAD

**Issue by rohit901** [manilarome/the-glorious-dotfiles#200]
Hi, I already saw a related Issue #169, in my case i think im using the correct wifi interface wlan0 but yet im not able to access wifi interface from title bar.

I'm using Ubuntu 20.04

I expect to change the wifi network when I click the wifi icon, see available networks etc.

Also could you let me know how to customize the apps in the bottom pannel, some of the apps don't open when I click in the bottom panel dock. 
When I click on the wifi icon this pops up.

Refer:
https://imgur.com/JNsj927

**Comment by rohit901** [comment]
Also, I'm really sorry for another silly question, I'm completely new to awesome WM. 
My file managher doesn't have that sick transparent looking UI/Theme as shown in your screenshots could you lemme know how to replicate that as well?

![20201115_120201](https://user-images.githubusercontent.com/30185369/99178569-68840100-273a-11eb-9bf4-1e51fcc15178.png)

**Comment by manilarome** [comment]
The default network manager is `iwctl`. So it will launch iwctl prompt if you click on the icon.

The file manager I am using is dolphin btw. So that's why you don't have the transparency. You are using nautilus.

You can fix all your problem by reading the [wiki](https://github.com/manilarome/the-glorious-dotfiles/wiki). Goodluck brother! Closing this now
