### ISSUE TITLE
[FEATURE REQUEST] Scrollable Notification Center

### ISSUE THREAD

**Issue by poiuedws** [manilarome/the-glorious-dotfiles#29]
since old notifications are not viewable until dismissing the new ones, a scrollbar would be a nice feature to have.

**Comment by manilarome** [comment]
> a scrollbar would be a nice feature to have.

Yep, that's one of my objectives. But, it's too complicated.
There are some of the information I got:
https://stackoverflow.com/questions/55936636/how-to-make-mouse-events-propagate-to-widgets-in-scroll-containers
https://www.reddit.com/r/awesomewm/comments/cii9u9/scrolling_widget_with_scrollbar/

**Comment by OliverLew** [comment]
Just my thoughts: maybe an alternative is dividing them into pages?

**Comment by manilarome** [comment]
Thanks for the suggestion. I'll try to implement that @OliverLew

**Comment by manilarome** [comment]
We have some progress, yow. But it will definitely take some time to finish because I don't feel so good.


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40349590/76059515-045d4a80-5fba-11ea-9c33-01b4be8ff3ac.gif)

**Comment by OliverLew** [comment]
Another thought:
Scroll discretely (not continuous). Additionally you can use the slider widget as a scroll bar. Here is a demo with textboxes:

![Peek 2020-04-18 11-23](https://user-images.githubusercontent.com/12032219/79641658-78029200-81cb-11ea-8c96-4da3732c9de5.gif)

<details>
<summary>The code of the demo:</summary>
<p>

```lua
local notifications = {}
for i = 1, 20 do
    table.insert(notifications, wibox.widget.textbox(
        string.format("No. %d\n\tSomething", i)
    ))
end
local slider = wibox.widget{
    maximum = 20,
    minimum = 1,
    forced_height = 24,
    forced_width = 24,
    handle_width = 48,
    handle_color = "#808080",
    bar_height = 24,
    bar_shape = gears.shape.rectangle,
    bar_color = "#202020",
    bar_active_color = "#202020",
    bar_margins = 0,
    widget = wibox.widget.slider,
}
local notification_list = wibox.widget {
    layout = wibox.layout.fixed.vertical
}
local notification_area = wibox.widget {
    nil,
    notification_list,
    {
        slider,
        direction = "west",
        forced_height = beautiful.bar_size,
        widget = wibox.container.rotate
    },
    layout = wibox.layout.align.horizontal
}
notification_area:buttons {
    awful.button( {}, 4, function() slider.value = slider.value - 1 end ),
    awful.button( {}, 5, function() slider.value = slider.value + 1 end ),
}
slider:connect_signal('property::value', function()
    local index = slider.value
    notification_list:reset()
    for i = index, index + 9 do
        if notifications[i] then
            notification_list:add(notifications[i])
        end
    end
end)
slider.value = 1
wibox {
    widget = notification_area,
    x = 300, y = 300,
    width = 360, height = 360,
    bg = "#404040",
    visible = true
}
```

</p>
</details>

I guess the only thing important here is to redraw the vertical layout with different starting point so it looks like it's scrollable (or it really is).

This only uses plain AwesomeWM widgets instead of inventing some new wheels, with only a small compromise. Will this work well with the notification boxes?

**Comment by manilarome** [comment]
Nice! Thanks for this. Will try this out! Hopefully it'll work as expected. :)

**Comment by manilarome** [comment]
We have some progress, although it's a bit clunky sometimes. The notification list vanishes when you scroll up to the end.

![out](https://user-images.githubusercontent.com/40349590/79686150-b8681b80-8270-11ea-9bed-29877e153159.gif)

We have to find a way to:
1. Show only the scrollbar if there's no more space in the notification layout.
2. Delete the notification widget in the table after closing the same notification in the layout. Emptying the table is easy but deleting the same widget in layout and table is not(for me. im noob in lua).
3. Fix the clunkiness.


Number `1` is the hardest to implement because we need to get the available space in the layout before showing the scrollbar/start the scrolling event.

**Comment by OliverLew** [comment]
Since I am also trying to do this at the time, I might as well share some more of my ideas:
For No. 4, I think you have to put the vertical layout (or the scrollbar only) in a fixed-height parent widget like in my demo.
For No. 2, I remember I played a little bit with the [destroyed signal](https://awesomewm.org/apidoc/core_components/naughty.notification.html#destroyed) of notifications. But I am not sure if we can use this to remove itself from tables and layouts. This problem seems indeed tricky :(
For No. 1, is it possible to check the available space with the `y` and `height` properties of the notification boxes?

**Comment by manilarome** [comment]
>  I think you have to put the vertical layout (or the scrollbar only) in a fixed-height parent widget like in my demo.

Yeah that will fix it :)

>  I remember I played a little bit with the destroyed signal of notifications. But I am not sure if we can use this to remove itself from tables and layouts. This problem seems indeed tricky :(

What if assign the widget's element in the table as its `id`?

```lua
    for i = index, index + 9 do
        if notifications[i] then
            local notif_widget = notifications[i]
            notif_widget.id = tostring(i)
            notification_list:add(notif_widget)
        end
    end
```

Then after closing the notification widget in the layout, use its `id` to delete the element in the table?

```lua
table.remove(notif_table, tonumber(notif_widget.id))?
```

This is just a guess tho. But I think it's the most plausible thing to do lol

> is it possible to check the available space with the y and height properties of the notification boxes?

I don't think that it's possible natively but using a hackish way will do probably. What if get the `screen.geometry.height` then get the height of the widgets **above** the notification area/layout then just do some math magic to determine the vertical space available? Then after every notification widget generation, check again the available space. It's  ~~a bit~~ complicated to do but I think it's possible.

**Comment by manilarome** [comment]
> What if assign the widget's element in the table as its id? Then after closing the notification widget in the layout, use its id to delete the element in the table?

So I tried this and it works perfectly. 

Now, the only problem we have is getting the available space in the layout/panel.

**Comment by manilarome** [comment]
Good news! I found an old thread that will give us the answer for our main problem(getting the height of the widget)!

This can be found [here](https://stackoverflow.com/questions/47648448/get-geometry-of-widgets-with-variable-size)

**Comment by manilarome** [comment]
#### Update:

It turns out that using a table and using the notification's element as id will cause a problem in a long run. So back to this

> Delete the notification widget in the table after closing the same notification in the layout. Emptying the table is easy but deleting the same widget in layout and table is not(for me. im noob in lua).

**Comment by ildar** [comment]
https://github.com/manilarome/awesome-glorious-widgets/issues/1 still can
partly solve this problem

**Comment by manilarome** [comment]
Oh yeah. I almost forgot about that. Can you tell me what are the types of notification we should group? Or are you talking about the same content? The problem with this is how can we know if they are the same type. The widgets(notifications) in the notification center are inside of a layout. `wibox.layout.fixed.vertical()`. And we are storing it in that layout using `the_layout:insert(1, the_notification_widget)`

**Comment by ildar** [comment]
same content, repeating notifications.
I understand that different people get very different set of notifications.
So I base on my experience. Repeating notification grouping would help a
lot in my case.

**Comment by manilarome** [comment]
> same content, repeating notifications.

Okay. We have a problem tho. Right now, the notification center is just a storage of the widgets created from the naughty data. Implemented [here](https://github.com/manilarome/the-glorious-dotfiles/blob/4de2b9777bea7ff81d1a50e049d8da9be15e847f/config/awesome/floppy/widget/notif-center/build-notifbox/init.lua#L67-L101). We can't really compare the content of the notification widgets(the notifications widgets displayed in the notification center are not really `naughty` but a bunch of `wibox.widgets` with a data from naughty) inside the notification right now. The only possible way to view the hidden notifications is by making the notifcenter scrollable. Either play with [this](https://stackoverflow.com/questions/55936636/how-to-make-mouse-events-propagate-to-widgets-in-scroll-containers) or the suggestion of @OliverLew

**Comment by ildar** [comment]
Oh! That explains why awesome sometimes get laggy.
Hundreds of widgets aren't fun

**Comment by manilarome** [comment]
> That explains why awesome sometimes get laggy. Hundreds of widgets aren't fun

Not really @ildar , the real thing that made the setups heavy than it should be are the tons of `gears.timer`, `awful.widget.watch` and the constant update/redraws. I'm talking about the hardware monitor(how ironic) and the widgets like wifi, battery, and of course the blur effect. The notification center is surprising lighter than the one I mentioned. It's because it only runs if there is a `request::display` signal detected. You can make it *less* laggy by removing/unusing them.

**Comment by manilarome** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40349590/81134010-ed20e600-8f85-11ea-997d-b6ceda5def1a.gif)

I managed to implement a scrollable notification center, but there's some limitations:

+ We only have *one* notification layout. So it means if you have a multihead setup, scrolling the notification center in monitor/screen 1 will also scroll the notification center in all monitors/screens.
+ There's no start/end point while scrolling. There's no "boundary" that will stop the user from scrolling. I can't really explain this well(English is not my strong suit). What I mean is if you reached the last notification and you scroll further down, instead of stopping the scrolling, it will continue and just iterate through all the notification *again*. But I think it's possible to implement this, I just need some time lol

**Comment by manilarome** [comment]
So yeah, I already implement the scrollable notif-center above. https://github.com/manilarome/the-glorious-dotfiles/pull/106/commits/71ac432acb274c33e0d81526db64cb5ef67ac844 Closing this now
