### ISSUE TITLE
How to hide titlebar on CSD applications

### ISSUE THREAD

**Issue by TaylanTatli** [manilarome/the-glorious-dotfiles#53]
I found `requests_no_titlebar` property but don't know how to implement it to gnawesome.

**Comment by manilarome** [comment]
Set the properties in `awesome/configuration/client/rules.lua`. :)

**Comment by manilarome** [comment]
My setup uses a custom property called `hide_titlebars`. Set/Add it to the client properties in the rules.lua so client will not show its titlebar.

**Comment by TaylanTatli** [comment]
Sorry English is not my native language, maybe i can't explain myself very well. It seems you can't set it by rules. Can you look here please: https://awesomewm.org/apidoc/core_components/client.html#requests_no_titlebar
sorry for troubling you

**Comment by manilarome** [comment]
>  It seems you can't set it by rules

Yes you can :) I'm using the snippet below to hide/don't show the client's titlebar:

```lua
	ruled.client.append_rule {
		id        = "hide_titlebars",
		rule_any  = {
			class    = {
				"feh",
				"Mugshot",
				"Pulseeffects"
			},
		},
		properties = { 
			skip_decoration = true,
			hide_titlebars = true,
			floating = true,
			ontop = true,
			placement = awful.placement.centered
		}
	}
```

You can also use the `requests_no_titlebar`, but in my setup, I'm using the custom property `hide_titlebars` because I'm using the arrange signal's [callback](https://github.com/manilarome/the-glorious-dotfiles/blob/da7e4ad120a98fdace91034a48a3dc180297cbf2/config/awesome/gnawesome/module/titlebar.lua#L261-L297) to manipulate the titlebar based on the tag layout. For example, the quake terminal will show its titlebar even we have `requests_no_titlebar` in its rule.

![image](https://user-images.githubusercontent.com/40349590/77822942-32a1f600-7132-11ea-968d-a524e4b092ab.png)

**Comment by TaylanTatli** [comment]
Oh, get it. Thank you for help. :)
