### ISSUE TITLE
[QUESTION][FLOPPY] How to setup dual monitors with different resolutions?

### ISSUE THREAD

**Issue by spiwocoal** [manilarome/the-glorious-dotfiles#58]
I recently got access to a small 1280x1024 monitor that I plugged to my 1920x1080 laptop, but upon connection, I only see the same as in my laptop's screen but cropped. I tried fixing this with `xrandr --auto --output DP2 --mode 1280x1024 --left-of eDP1`, but now I just see the sidebar in my external monitor and the top panel resized in my laptop screen to the size it would have in my external screen.

This is what I see in the 1280x1024 screen.
![Left Screen](https://user-images.githubusercontent.com/30442253/78193137-2d092080-7450-11ea-96ca-c0c7e3ec3622.png)

And this is what I see in the 1920x1080 screen.
![Right Screen](https://user-images.githubusercontent.com/30442253/78193592-3e066180-7451-11ea-91db-7e14cf44df8d.png)

I would like to know if it's possible to have the sidebar in both screens, and if there's a way to have the top panel correctly sized in my laptop screen.

Thanks in advance.

**Comment by manilarome** [comment]
> I would like to know if it's possible to have the sidebar in both screens

Change [these lines](https://github.com/manilarome/the-glorious-dotfiles/blob/03ed4a650a2bf502f450eedb75646eb46313a9a0/config/awesome/floppy/layout/init.lua#L9-L19) to :

```lua
	-- Create the left_panel
	s.left_panel = left_panel(s)
	-- Create the Top bar
	s.top_panel = top_panel(s, true)
```

Then, change [this one](https://github.com/manilarome/the-glorious-dotfiles/blob/03ed4a650a2bf502f450eedb75646eb46313a9a0/config/awesome/floppy/configuration/keys/global.lua#L412) to 

```lua
            focused.left_panel:toggle()
```

so you can open the left panel on focused screen instead of just primary.


>  and if there's a way to have the top panel correctly sized in my laptop screen.

Reload awesome after plugging in the monitor, that should fix it. :)

**Comment by spiwocoal** [comment]
Thank you so much! This worked immediately! 
It's amazing seeing people like you so engaged in helping others! :smile:

**Comment by manilarome** [comment]
No problem, mate! I just love helping the community. :)
