### ISSUE TITLE
[BUG][Floppy] Lock Screen - Bottom 1/4 of screen cut off

### ISSUE THREAD

**Issue by Unaidedsteak** [manilarome/the-glorious-dotfiles#81]
Monitor setup:

2560x1440p (landscape) primary monitor
1920x1080p (portrait) secondary monitor

Issue:

When locking screen using Super + L , the lock screen only covers the top 3/4 of the primary monitor, the secondary monitor is covered completely.
![2020-04-09-163838_3681x1920_scrot](https://user-images.githubusercontent.com/14805497/78913725-5691ff80-7a81-11ea-958b-83c6da58340c.png)

Am happy to try and fix this if you can point me in the right direction

**Comment by manilarome** [comment]
> Am happy to try and fix this if you can point me in the right direction

Please do for  I can't test it because I only have a 1366x768 resolution. This is [where](https://github.com/manilarome/the-glorious-dotfiles/blob/473d1afa98ba7a8b21514ab01b277231bf2460a7/config/awesome/floppy/module/lockscreen.lua#L47-L48) we set the geometry of the lockscreen for the main/primary monitor. Then [this](https://github.com/manilarome/the-glorious-dotfiles/blob/473d1afa98ba7a8b21514ab01b277231bf2460a7/config/awesome/floppy/module/lockscreen.lua#L693-L701) is where awesome iterate through all the screen to generate the lockscreen for each screen. 

Note that we have a separate lockscreen for the index 1 screen and the extended monitor. Awesome is the one who sets the width and height for the lockscreen so I'm not sure why is the lockscreen so small in your primary monitor.

**Comment by ildar** [comment]
> I only have a 1366x768 resolution

You can temporarily change resolution with `xrandr`

**Comment by manilarome** [comment]
> You can temporarily change resolution with `xrandr` 

How to apply 2560x1440p tho? Because this resolution is not found in available modes @ildar .

**Comment by ildar** [comment]
xrandr --output MONx --size XxY
or alike. man xandr

**Comment by manilarome** [comment]
I manage to force my resolution to 2560x1440 using 

```bash
xrandr --output LVDS1 --panning 2560x1440 --scale 1.0x1.0
```

![20200410_185145](https://user-images.githubusercontent.com/40349590/78986009-d640cc80-7b5c-11ea-9d95-dc25df23ac1f.png)

And this is the lockscreen:

![nani](https://user-images.githubusercontent.com/40349590/78986098-07b99800-7b5d-11ea-8f90-1141e99d925b.png)
